# Generated by Django 5.1.5 on 2025-08-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotel_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(default='hotel_default.png', upload_to='menu'),
        ),
    ]
